Add mssql_ad_keytab_file to allow users provide a pre-created keytab

diff --git a/tasks/main.yml b/tasks/main.yml
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -670,168 +670,181 @@
         name: adutil
         state: present
 
-    - name: Print credential caches to check if AD principal exists
-      command: klist -l
-      register: __mssql_klist
-      changed_when: false
-      failed_when: false
+    - name: Create keytab file
+      when: mssql_ad_keytab_file is none
+      block:
+        - name: Print credential caches to check if AD principal exists
+          command: klist -l
+          register: __mssql_klist
+          changed_when: false
+          failed_when: false
 
-    # Do not fail when there are no tickets
-    - name: Print the status of credential cache for {{ __mssql_kinit_user }}
-      shell: >-
-        set -euo pipefail;
-        klist -l $(klist -l | grep {{ __mssql_kinit_user }} | awk '{print $2}')
-      register: __mssql_klist_kinit_user
-      when: __mssql_kinit_user in __mssql_klist.stdout
-      changed_when: false
+        # Do not fail when there are no tickets
+        - name: Print the status of credential cache for {{ __mssql_kinit_user }}
+          shell: >-
+            set -euo pipefail;
+            klist -l $(klist -l | grep {{ __mssql_kinit_user }} | awk '{print $2}')
+          register: __mssql_klist_kinit_user
+          when: __mssql_kinit_user in __mssql_klist.stdout
+          changed_when: false
 
-    - name: Obtain Kerberos ticket of the AD user {{ ad_integration_user }}
-      shell: >-
-        set -euo pipefail;
-        echo {{ ad_integration_password | quote }}
-        | kinit {{ __mssql_kinit_user }}
-      when: >-
-        (__mssql_kinit_user not in __mssql_klist.stdout)
-        or
-        ("(Expired)" in __mssql_klist_kinit_user.stdout | d())
-      no_log: true
-      changed_when: true
+        - name: Obtain Kerberos ticket of the AD user {{ ad_integration_user }}
+          shell: >-
+            set -euo pipefail;
+            echo {{ ad_integration_password | quote }}
+            | kinit {{ __mssql_kinit_user }}
+          when: >-
+            (__mssql_kinit_user not in __mssql_klist.stdout)
+            or
+            ("(Expired)" in __mssql_klist_kinit_user.stdout | d())
+          no_log: true
+          changed_when: true
 
-    # Do not fail if account does not exist
-    - name: Check if SQL user exists {{ mssql_ad_sql_user_name }}
-      command: >-
-        adutil account exists
-        --name {{ mssql_ad_sql_user_name }}
-        --accept-eula
-      register: __mssql_adutil_account_exists
-      changed_when: false
-      failed_when: false
+        # Do not fail if account does not exist
+        - name: Check if SQL user exists {{ mssql_ad_sql_user_name }}
+          command: >-
+            adutil account exists
+            --name {{ mssql_ad_sql_user_name }}
+            --accept-eula
+          register: __mssql_adutil_account_exists
+          changed_when: false
+          failed_when: false
 
-    - name: Verify password provided for user {{ mssql_ad_sql_user_name }}
-      command: >-
-        sshpass -p {{ mssql_ad_sql_password | quote }}
-        ssh -o StrictHostKeyChecking=no
-        -l {{ mssql_ad_sql_user_name }}@{{ ad_integration_realm }}
-        {{ ansible_fqdn }} id
-      register: __mssql_sql_user_ssh
-      ignore_errors: true
-      changed_when: false
-      when: __mssql_adutil_account_exists.stdout | bool
-      no_log: true
+        - name: Verify password provided for user {{ mssql_ad_sql_user_name }}
+          command: >-
+            sshpass -p {{ mssql_ad_sql_password | quote }}
+            ssh -o StrictHostKeyChecking=no
+            -l {{ mssql_ad_sql_user_name }}@{{ ad_integration_realm }}
+            {{ ansible_fqdn }} id
+          register: __mssql_sql_user_ssh
+          ignore_errors: true
+          changed_when: false
+          when: __mssql_adutil_account_exists.stdout | bool
+          no_log: true
 
-    - name: Update password for the SQL user {{ mssql_ad_sql_user_name }}
-      command: >-
-        adutil account setpassword
-        --name {{ mssql_ad_sql_user_name }}
-        --password {{ mssql_ad_sql_password | quote }}
-      when: __mssql_sql_user_ssh is failed
-      no_log: true
-      changed_when: true
+        - name: Update password for the SQL user {{ mssql_ad_sql_user_name }}
+          command: >-
+            adutil account setpassword
+            --name {{ mssql_ad_sql_user_name }}
+            --password {{ mssql_ad_sql_password | quote }}
+          when: __mssql_sql_user_ssh is failed
+          no_log: true
+          changed_when: true
 
-    - name: In AD server create user {{ mssql_ad_sql_user_name }}
-      command: >-
-        adutil user create
-        --name {{ mssql_ad_sql_user_name }}
-        --password {{ mssql_ad_sql_password | quote }}
-        --distname {{ mssql_ad_sql_user_dn | quote }}
-        --debug
-      register: __mssql_adutil_user_create
-      when: not __mssql_adutil_account_exists.stdout | bool
-      no_log: true
-      changed_when: true
+        - name: In AD server create user {{ mssql_ad_sql_user_name }}
+          command: >-
+            adutil user create
+            --name {{ mssql_ad_sql_user_name }}
+            --password {{ mssql_ad_sql_password | quote }}
+            --distname {{ mssql_ad_sql_user_dn | quote }}
+            --debug
+          register: __mssql_adutil_user_create
+          when: not __mssql_adutil_account_exists.stdout | bool
+          no_log: true
+          changed_when: true
 
-    - name: Get SPNs for the principal {{ mssql_ad_sql_user_name }}
-      command: adutil spn show --name {{ mssql_ad_sql_user_name }}
-      register: __mssql_adutil_spn_show
-      changed_when: false
+        - name: Get SPNs for the principal {{ mssql_ad_sql_user_name }}
+          command: adutil spn show --name {{ mssql_ad_sql_user_name }}
+          register: __mssql_adutil_spn_show
+          changed_when: false
 
-    - name: Register SPNs to the principal {{ mssql_ad_sql_user_name }}
-      command: >-
-        adutil spn addauto
-        --name {{ mssql_ad_sql_user_name }}
-        --spn-service MSSQLSvc
-        --spn-host {{ ansible_fqdn }}
-        --spn-port {{ mssql_tcp_port }}
-        --yes
-        --debug
-      register: __mssql_adutil_spn_addauto
-      changed_when: >-
-        not "Type or value exists"
-        in __mssql_adutil_spn_addauto.stdout
-      when: >-
-        not "MSSQLSvc/" ~ ansible_fqdn ~ ":" ~ mssql_tcp_port
-        in __mssql_adutil_spn_show.stdout
+        - name: Register SPNs to the principal {{ mssql_ad_sql_user_name }}
+          command: >-
+            adutil spn addauto
+            --name {{ mssql_ad_sql_user_name }}
+            --spn-service MSSQLSvc
+            --spn-host {{ ansible_fqdn }}
+            --spn-port {{ mssql_tcp_port }}
+            --yes
+            --debug
+          register: __mssql_adutil_spn_addauto
+          changed_when: >-
+            not "Type or value exists"
+            in __mssql_adutil_spn_addauto.stdout
+          when: >-
+            not "MSSQLSvc/" ~ ansible_fqdn ~ ":" ~ mssql_tcp_port
+            in __mssql_adutil_spn_show.stdout
 
-    - name: Get kvno of the SPN host
-      command: adutil account kvno {{ mssql_ad_sql_user_name }}
-      register: __mssql_kvno
-      changed_when: false
+        - name: Get kvno of the SPN host
+          command: adutil account kvno {{ mssql_ad_sql_user_name }}
+          register: __mssql_kvno
+          changed_when: false
 
-    - name: Get stats of the keytab file
-      stat:
-        path: "{{ __mssql_keytab_path }}"
-      register: __mssql_keytab_stat
+        - name: Get stats of the keytab file
+          stat:
+            path: "{{ __mssql_keytab_path }}"
+          register: __mssql_keytab_stat
 
-    - name: Get keytab properties
-      command: klist -edk {{ __mssql_keytab_path }}
-      changed_when: false
-      when: __mssql_keytab_stat.stat.exists | bool
-      register: __mssql_keytab_properties
+        - name: Get keytab properties
+          command: klist -edk {{ __mssql_keytab_path }}
+          changed_when: false
+          when: __mssql_keytab_stat.stat.exists | bool
+          register: __mssql_keytab_properties
 
-    - name: Create keytab
-      command: >-
-        adutil keytab createauto
-        --password {{ mssql_ad_sql_password | quote }}
-        --path {{ __mssql_keytab_path }}
-        --spn-port {{ mssql_tcp_port }}
-        --spn-host {{ ansible_fqdn }}
-        --spn-service MSSQLSvc
-        --kvno {{ __mssql_kvno.stdout }}
-        --enctype aes256-cts-hmac-sha1-96,aes128-cts-hmac-sha1-96
-        --yes
-      when:
-        - >-
-          not __mssql_kvno.stdout ~ " MSSQLSvc/" ~ ansible_fqdn ~ ":"
-          ~ mssql_tcp_port ~ "@" ~ ad_integration_realm | upper
-          ~ " (aes256-cts-hmac-sha1-96)"
-          in __mssql_keytab_properties.stdout | d()
-        - >-
-          not __mssql_kvno.stdout ~ " MSSQLSvc/" ~ ansible_fqdn ~ ":"
-          ~ mssql_tcp_port ~ "@" ~ ad_integration_realm | upper
-          ~ " (aes128-cts-hmac-sha1-96)"
-          in __mssql_keytab_properties.stdout | d()
-      notify: Restart the mssql-server service
-      no_log: true
-      changed_when: true
+        - name: Create keytab
+          command: >-
+            adutil keytab createauto
+            --password {{ mssql_ad_sql_password | quote }}
+            --path {{ __mssql_keytab_path }}
+            --spn-port {{ mssql_tcp_port }}
+            --spn-host {{ ansible_fqdn }}
+            --spn-service MSSQLSvc
+            --kvno {{ __mssql_kvno.stdout }}
+            --enctype aes256-cts-hmac-sha1-96,aes128-cts-hmac-sha1-96
+            --yes
+          when:
+            - >-
+              not __mssql_kvno.stdout ~ " MSSQLSvc/" ~ ansible_fqdn ~ ":"
+              ~ mssql_tcp_port ~ "@" ~ ad_integration_realm | upper
+              ~ " (aes256-cts-hmac-sha1-96)"
+              in __mssql_keytab_properties.stdout | d()
+            - >-
+              not __mssql_kvno.stdout ~ " MSSQLSvc/" ~ ansible_fqdn ~ ":"
+              ~ mssql_tcp_port ~ "@" ~ ad_integration_realm | upper
+              ~ " (aes128-cts-hmac-sha1-96)"
+              in __mssql_keytab_properties.stdout | d()
+          notify: Restart the mssql-server service
+          no_log: true
+          changed_when: true
 
-    - name: Add an entry in the keytab for the principal name and password
-      command: >-
-        adutil keytab create
-        --password {{ mssql_ad_sql_password | quote }}
-        --path {{ __mssql_keytab_path }}
-        --principal {{ mssql_ad_sql_user_name }}
-        --kvno {{ __mssql_kvno.stdout }}
-        --enctype aes256-cts-hmac-sha1-96,aes128-cts-hmac-sha1-96
-      when:
-        - >-
-          not __mssql_kvno.stdout ~ " " ~ mssql_ad_sql_user_name ~ "@"
-          ~ ad_integration_realm | upper ~ " (aes256-cts-hmac-sha1-96)"
-          in __mssql_keytab_properties.stdout | d()
-        - >-
-          not __mssql_kvno.stdout ~ " " ~ mssql_ad_sql_user_name ~ "@"
-          ~ ad_integration_realm | upper ~ " (aes128-cts-hmac-sha1-96)"
-          in __mssql_keytab_properties.stdout | d()
-      notify: Restart the mssql-server service
-      no_log: true
-      changed_when: true
+        - name: Add an entry in the keytab for the principal name and password
+          command: >-
+            adutil keytab create
+            --password {{ mssql_ad_sql_password | quote }}
+            --path {{ __mssql_keytab_path }}
+            --principal {{ mssql_ad_sql_user_name }}
+            --kvno {{ __mssql_kvno.stdout }}
+            --enctype aes256-cts-hmac-sha1-96,aes128-cts-hmac-sha1-96
+          when:
+            - >-
+              not __mssql_kvno.stdout ~ " " ~ mssql_ad_sql_user_name ~ "@"
+              ~ ad_integration_realm | upper ~ " (aes256-cts-hmac-sha1-96)"
+              in __mssql_keytab_properties.stdout | d()
+            - >-
+              not __mssql_kvno.stdout ~ " " ~ mssql_ad_sql_user_name ~ "@"
+              ~ ad_integration_realm | upper ~ " (aes128-cts-hmac-sha1-96)"
+              in __mssql_keytab_properties.stdout | d()
+          notify: Restart the mssql-server service
+          no_log: true
+          changed_when: true
 
-    - name: Ensure correct permissions and ownership on the keytab
-      file:
-        path: "{{ __mssql_keytab_path }}"
+        - name: Ensure correct permissions and ownership on the keytab
+          file:
+            path: "{{ __mssql_keytab_path }}"
+            owner: mssql
+            group: mssql
+            mode: 0440
+          notify: Restart the mssql-server service
+
+    - name: Fetch keytab file to host
+      when: mssql_ad_keytab_file is not none
+      copy:
+        src: "{{ mssql_ad_keytab_file }}"
+        remote_src: "{{ mssql_ad_keytab_remote_src }}"
+        dest: "{{ __mssql_keytab_path }}"
         owner: mssql
         group: mssql
         mode: 0440
-      notify: Restart the mssql-server service
 
     - name: Configure the network.kerberoskeytabfile setting
       include_tasks: mssql_conf_setting.yml
